// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const LOCAL_AUTH_STORAGE_KEY = 'skillswap-local-auth';

function createDemoSupabaseClient() {
  const createDemoUser = (email: string, fullName?: string) => ({
    id: `demo-${Math.random().toString(36).slice(2, 10)}`,
    email,
    user_metadata: { full_name: fullName ?? email.split('@')[0] },
  });

  const readStoredSession = () => {
    if (typeof window === 'undefined') return null;
    const raw = window.localStorage.getItem(LOCAL_AUTH_STORAGE_KEY);
    if (!raw) return null;

    try {
      return JSON.parse(raw);
    } catch {
      window.localStorage.removeItem(LOCAL_AUTH_STORAGE_KEY);
      return null;
    }
  };

  const persistSession = (session: any) => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(LOCAL_AUTH_STORAGE_KEY, JSON.stringify(session));
    }
    return session;
  };

  const clearSession = () => {
    if (typeof window !== 'undefined') {
      window.localStorage.removeItem(LOCAL_AUTH_STORAGE_KEY);
    }
  };

  return {
    auth: {
      onAuthStateChange(callback: (event: string, session: any) => void) {
        const initialSession = readStoredSession();
        callback('INITIAL_SESSION', initialSession ?? null);
        return { data: { subscription: { unsubscribe() {} } } };
      },
      async getSession() {
        return { data: { session: readStoredSession() ?? null }, error: null };
      },
      async getUser() {
        const session = readStoredSession();
        return { data: { user: session?.user ?? null }, error: null };
      },
      async signInWithPassword({ email, password }: { email: string; password: string }) {
        if (!email || !password) {
          return {
            data: { user: null, session: null },
            error: { message: 'Email and password are required.' },
          };
        }

        const user = createDemoUser(email);
        const session = persistSession({ user, access_token: 'demo-token', refresh_token: 'demo-token' });
        return { data: { user, session }, error: null };
      },
      async signUp({ email, password, options }: { email: string; password: string; options?: any }) {
        if (!email || !password || password.length < 6) {
          return {
            data: { user: null, session: null },
            error: { message: 'Password must be at least 6 characters.' },
          };
        }

        const fullName = options?.data?.full_name;
        const user = createDemoUser(email, fullName);
        const session = persistSession({ user, access_token: 'demo-token', refresh_token: 'demo-token' });
        return { data: { user, session }, error: null };
      },
      async signOut() {
        clearSession();
        return { error: null };
      },
    },
  } as any;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Missing env vars; running in local demo mode.');
    return createDemoSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

